# Generated by Django 3.1.2 on 2020-10-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201014_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogs',
            name='vlogurl',
            field=models.URLField(null=True),
        ),
    ]
