# Generated by Django 3.1.2 on 2020-11-06 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vlogs_vlogurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('banner', models.ImageField(upload_to='')),
            ],
        ),
    ]
