# Generated by Django 3.1.2 on 2020-11-24 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('vlogurl', models.URLField(null=True)),
                ('banner', models.ImageField(upload_to='')),
                ('views', models.IntegerField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.college')),
            ],
        ),
    ]
