# Generated by Django 3.1.2 on 2020-10-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='file',
            field=models.FileField(default='Null', upload_to='data'),
        ),
    ]
