# Generated by Django 3.1.2 on 2020-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requests_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='college_email',
        ),
        migrations.AddField(
            model_name='leads',
            name='college',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='college_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='request',
            field=models.TextField(null=True),
        ),
    ]
