# Generated by Django 3.1.2 on 2020-10-14 18:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_college_collegename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogs',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
